# Introduction

This notebook demonstrates code that will connect to, and import from, a Microsoft Access data file. In this case `IPEDS201617.accdb` which is among many `.accdb` files available from the [IPEDS Microsoft Access data files](https://nces.ed.gov/ipeds/use-the-data/download-access-database).

## Configuration note

This example was developed with in a 64bit Python enviornment. To function, your environment should have a 64bit version of Microsoft Office Installed (the default is 32bit). In addition to having installed a 64bit version of Microsoft Office this code also required an installation of the 64bit [Microsoft Acces Database Engine 2010](https://www.microsoft.com/en-US/download/details.aspx?id=13255). Documentation for `pyodbc` [here](https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-Microsoft-Access) and this [Feb 22 2018 Stackoverflow Answer from Grimravus](https://stackoverflow.com/a/48937535/9572143) provide additional background.

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import pyodbc
import os

In [2]:
# Build file location using os.path.join() to ensure cross-platform operations.
db_file = (os.path.join('data', 'IPEDS201617.accdb'))

In [3]:
# Check to ensure file exists.
os.path.isfile(db_file)

True

In [4]:
# Open ODBC connection (See configuration notes above, if errors).
conn = pyodbc.connect(
    r'Driver={Microsoft Access Driver (*.mdb, *.accdb)};' +
    r'Dbq=' + db_file + r';')

In [5]:
# Get directory information for all institutions & display head.
data = pd.read_sql('SELECT * FROM hd2016', conn)
data.head()

,UNITID,INSTNM,IALIAS,ADDR,CITY,STABBR,ZIP,FIPS,OBEREG,CHFNM,...,CBSATYPE,CSA,NECTA,COUNTYCD,COUNTYNM,CNGDSTCD,LONGITUD,LATITUDE,DFRCGID,DFRCUSCG
0,100654,Alabama A & M University,AAMU,4900 Meridian Street,Normal,AL,35762,1,5,"Dr. Andrew Hugine, Jr.",...,1,290,-2,1089,Madison County,105,-86.568502,34.783368,128,1
1,100663,University of Alabama at Birmingham,,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,1,5,Ray L. Watts,...,1,142,-2,1073,Jefferson County,107,-86.799345,33.505697,115,1
2,100690,Amridge University,Southern Christian University |Regions University,1200 Taylor Rd,Montgomery,AL,36117-3553,1,5,Michael Turner,...,1,-2,-2,1101,Montgomery County,102,-86.174010,32.362609,236,2
3,100706,University of Alabama in Huntsville,UAH |University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,1,5,Robert A. Altenkirch,...,1,290,-2,1089,Madison County,105,-86.640449,34.724557,118,2
4,100724,Alabama State University,,915 S Jackson Street,Montgomery,AL,36104-0271,1,5,Leon Wilson,...,1,-2,-2,1101,Montgomery County,107,-86.295677,32.364317,136,1

In [6]:
# Get directory information for specific institutions & display results
data = pd.read_sql('SELECT * FROM hd2016 WHERE UNITID=240444', conn)

In [7]:
for var in data.columns:
    print('{:>12} : {:<}'.format(var, data[var][0]))
    
# Below the extensive output below is an alternate display option.

      UNITID : 240444
      INSTNM : University of Wisconsin-Madison
      IALIAS :
        ADDR : 500 Lincoln Dr
        CITY : Madison
      STABBR : WI
         ZIP : 53706-1380
        FIPS : 55
      OBEREG : 3
       CHFNM : Rebecca Blank
    CHFTITLE : Chancellor
     GENTELE : 6082632400
         EIN : 391805963
        DUNS : 170403497
       OPEID : 00389500
     OPEFLAG : 1
     WEBADDR : www.wisc.edu
    ADMINURL : www.wisc.edu/admissions/
     FAIDURL : www.finaid.wisc.edu
     APPLURL : https://www.commonapp.org/
    NPRICURL : www.finaid.wisc.edu/award-estimator.php
      VETURL : veterans.wisc.edu
      ATHURL : apir.wisc.edu/retention.htm
     DISAURL : mcburney.wisc.edu/
      SECTOR : 1
     ICLEVEL : 1
     CONTROL : 1
     HLOFFER : 9
     UGOFFER : 1
     GROFFER : 1
    HDEGOFR1 : 11
    DEGGRANT : 1
        HBCU : 2
    HOSPITAL : 2
     MEDICAL : 1
      TRIBAL : 2
      LOCALE : 12
    OPENPUBL : 1
         ACT : A
       NEWID : -2
     DEATHYR : -2
    CLOSEDAT : -2
    CYACTIVE : 1
     POSTSEC : 1
     PSEFLAG : 1
    PSET4FLG : 1
      RPTMTH : 1
     INSTCAT : 2
    C15BASIC : 15
     C15IPUG : 11
    C15IPGRD : 14
    C15UGPRF : 14
    C15ENPRF : 5
    C15SZSET : 16
     CCBASIC : 15
    CARNEGIE : 15
    LANDGRNT : 1
    INSTSIZE : 5
    F1SYSTYP : 1
    F1SYSNAM : University of Wisconsin System
    F1SYSCOD : 155010
        CBSA : 31540
    CBSATYPE : 1
         CSA : 357
       NECTA : -2
    COUNTYCD : 55025
    COUNTYNM : Dane County
    CNGDSTCD : 5502
    LONGITUD : -89.405356
    LATITUDE : 43.073858
     DFRCGID : 113
    DFRCUSCG : 1

In [8]:
# Alternate single or few (1-3 insts) institutaional display option.
data = pd.read_sql('SELECT * FROM hd2016 WHERE UNITID IN (240444, 238263, 153658)', conn)
data.transpose()

,0,1,2
UNITID,153658,238263,240444
INSTNM,University of Iowa,Madison Area Technical College,University of Wisconsin-Madison
IALIAS,Iowa|UI,Madison College,
ADDR,101 Jessup Hall,1701 Wright St,500 Lincoln Dr
CITY,Iowa City,Madison,Madison
STABBR,IA,WI,WI
ZIP,52242-1316,53704-2599,53706-1380
FIPS,19,55,55
OBEREG,4,3,3
CHFNM,Bruce Harreld,Jack E Daniels III,Rebecca Blank
CHFTITLE,President,President,Chancellor
GENTELE,3193353500,6082466100,6082632400
EIN,426004813,391086718,391805963
DUNS,062761617,073849200|102217593|120703392|618159800|078396475,170403497
OPEID,00189200,00400700,00389500
OPEFLAG,1,1,1
WEBADDR,www.uiowa.edu,madisoncollege.edu,www.wisc.edu
ADMINURL,admissions.uiowa.edu,madisoncollege.edu/apply,www.wisc.edu/admissions/
FAIDURL,financialaid.uiowa.edu/,madisoncollege.edu/financial-aid,www.finaid.wisc.edu
APPLURL,admissions.uiowa.edu/apply,madisoncollege.edu/apply,https://www.commonapp.org/
NPRICURL,npc.collegeboard.org/student/app/uiowa,ire.madisoncollege.edu/heoa-calc/npcalc.htm,www.finaid.wisc.edu/award-estimator.php
VETURL,registrar.uiowa.edu/gi-bill,madisoncollege.edu/veterans-benefits,veterans.wisc.edu
ATHURL,www.ncaa.org/about/resources/research/graduati...,madisoncollege.edu/right-know,apir.wisc.edu/retention.htm
DISAURL,sds.studentlife.uiowa.edu/,https://madisoncollege.edu/disability-resource...,mcburney.wisc.edu/
SECTOR,1,1,1
ICLEVEL,1,1,1
CONTROL,1,1,1
HLOFFER,9,6,9
UGOFFER,1,1,1
GROFFER,1,1,1
...,...,...,...
CYACTIVE,1,1,1
POSTSEC,1,1,1
PSEFLAG,1,1,1
PSET4FLG,1,1,1
RPTMTH,1,1,1
INSTCAT,2,4,2
C15BASIC,15,14,15
C15IPUG,14,5,11
C15IPGRD,14,0,14
C15UGPRF,15,5,14
C15ENPRF,4,3,5
C15SZSET,16,12,16
CCBASIC,15,3,15
CARNEGIE,15,40,15
LANDGRNT,2,2,1
INSTSIZE,5,4,5
F1SYSTYP,2,1,1
F1SYSNAM,...,Wisconsin Technical College System ...,University of Wisconsin System ...
F1SYSCOD,-2,155020,155010
CBSA,26980,31540,31540
CBSATYPE,1,1,1
CSA,168,357,357
NECTA,-2,-2,-2
COUNTYCD,19103,55025,55025
COUNTYNM,Johnson County,Dane County,Dane County
CNGDSTCD,1902,5502,5502
LONGITUD,-91.5364,-89.3279,-89.4054
LATITUDE,41.6619,43.1218,43.0739
DFRCGID,114,214,113
DFRCUSCG,1,1,1

In [9]:
# This example includes a 'Tables16' table which lists the available tables.
data = pd.read_sql('SELECT * FROM Tables16', conn)

In [10]:
data

,SurveyOrder,SurveyNumber,Survey,YearCoverage,TableName,Tablenumber,TableTitle,Description,Release,Release date
0,10,1,Institutional Characteristics,Academic year 2016-17,HD2016,10,Directory information,This table contains directory information for ...,Provisional/final (institutions will not be a...,January 2018
1,10,1,Institutional Characteristics,Academic year 2016-17,FLAGS2016,11,Response status for all survey components,This table contains response status informatio...,Provisional,January 2018
2,10,1,Institutional Characteristics,Academic year 2016-17,IC2016,12,"Educational offerings, organization, admission...",This table contains data on program and award ...,Provisional,January 2018
3,10,1,Institutional Characteristics,Academic year 2016-17,IC2016_AY,13,Student charges for academic year programs,This table contains data on student charges fo...,Provisional/final (institutions will not be a...,January 2018
4,10,1,Institutional Characteristics,Academic year 2016-17,IC2016_PY,14,Student charges by program (vocational programs),This table contains data on student charges by...,Provisional/final (institutions will not be a...,January 2018
5,10,1,Institutional Characteristics,Academic year 2016-17,DRVIC2016,15,Frequently used derived variables (IC): Total ...,This table contains derived variables for tota...,Provisional (institutions will not be allowed...,January 2018
6,10,1,Institutional Characteristics,Academic year 2016-17,IC2016MISSION,16,Mission statement,This table contains institution's mission stat...,Provisional,January 2018
7,10,1,Institutional Characteristics,Academic year 2016-17,CUSTOMCGIDS2016,17,Custom comparison groups,This table contains custom comparison groups s...,Provisional/final (institutions will not be a...,January 2018
8,20,2,Fall Enrollment,Fall 2016,EF2016,20,"Gender, attendance status, and level of studen...",This table contains the number of students enr...,Provisional,December 2017
9,20,2,Fall Enrollment,Fall 2016,EF2016A,21,"Race/ethnicity, gender, attendance status, and...",This table contains the number of students enr...,Provisional,December 2017
10,20,2,Fall Enrollment,Fall 2016,EF2016CP,22,"Major field of study, race/ethnicity, gender, ...",This table contains the number of students enr...,Provisional,December 2017
11,20,2,Fall Enrollment,Fall 2016,EF2016B,23,"Age category, gender, attendance status, and l...",This table contains the number of students enr...,Provisional,December 2017
12,20,2,Fall Enrollment,Fall 2016,EF2016C,24,Residence and migration of first-time freshman...,This table contains the number of first-time f...,Provisional,December 2017
13,20,2,Fall Enrollment,Fall 2016,EF2016D,25,"Total entering class, retention rates, and stu...",This table contains data on the total entering...,Provisional,December 2017
14,20,2,Fall Enrollment,Fall 2016,EF2016A_DIST,26,Distance education status and level of student...,This table contains the number of students enr...,Provisional,December 2017
15,20,2,Fall Enrollment,Fall 2016,DRVEF2016,27,Frequently used derived variables (EF): Fall e...,Table includes total full- and part-time enrol...,Provisional,December 2017
16,30,3,Completions,"July 1, 2015 - June 30, 2016",C2016_A,30,Awards/degrees conferred by program (6-digit C...,This table contains the number of awards by ty...,Provisional,January 2018
17,30,3,Completions,"July 1, 2015 - June 30, 2016",C2016_B,31,"Number of students receiving awards/degrees, b...",This table contains the number of students who...,Provisional,January 2018
18,30,3,Completions,"July 1, 2015 - June 30, 2016",C2016_C,32,"Number of students receiving awards/degrees, b...",This table contains the number of students rec...,Provisional,January 2018
19,30,3,Completions,"July 1, 2015 - June 30, 2016",C2016DEP,33,Number of programs offered and number of progr...,This file contains the number of programs offe...,Provisional,January 2018
20,30,3,Completions,"July 1, 2015 - June 30, 2016",DRVC2016,34,Frequently used derived variables (C): Complet...,Table includes number of degrees or certificat...,Provisional,January 2018
21,60,6,Finance,Fiscal year 2016,F1516_F1A,60,Public institutions - GASB 34/35: Fiscal year ...,This table contains institutional finance data...,Provisional,December 2017
22,60,6,Finance,Fiscal year 2016,F1516_F2,61,Private not-for-profit institutions or Public ...,This table contains institutional finance data...,Provisional,December 2017
23,60,6,Finance,Fiscal year 2016,F1516_F3,62,Private for-profit institutions: Fiscal year 2...,This table contains institutional finance data...,Provisional,December 2017
24,60,6,Finance,Fiscal year 2016,DRVF2016,63,Frequently used/derived variables Finance (F):...,Table includes the following financial indicat...,Provisional,December 2017
25,40,7,Student Financial Aid,"July 1, 2015 - June 30, 2016",SFA1516_P1,70,Student financial aid: 2015-16,This table contains data on the number of full...,Provisional,December 2017
26,40,7,Student Financial Aid,"July 1, 2015 - June 30, 2016",SFA1516_P2,71,Student financial aid and net price: 2015-16,This table contains the average net price at e...,Provisional,December 2017
27,40,7,Student Financial Aid,"July 1, 2015 - June 30, 2016",SFAV1516,72,Military Servicemembers and Veteran's Benefits...,This file contains data for students receiving...,Provisional,December 2017
28,50,8,Graduation Rates,"Status of student as of August 31, 2016",GR2016,80,"Graduation rate data, 150% of normal time to c...",This table contains the graduation rate status...,Provisional,December 2017
29,50,8,Graduation Rates,"Status of student as of August 31, 2016",GR2016_L2,81,"Graduation rate data, 150% of normal time to c...",This table contains the graduation rate status...,Provisional,December 2017
30,50,8,Graduation Rates,"Status of student as of August 31, 2016",GR2016_PELL_SSL,82,Graduation rate data for Pell Grant and Subsid...,This file contains the graduation rate status ...,Provisional,December 2017
31,50,8,Graduation Rates,"Status of student as of August 31, 2016",GR200_16,83,"Graduation rate data, 200% of normal time to c...",This table contains the graduation rate status...,Provisional,December 2017
32,50,8,Graduation Rates,"Status of student as of August 31, 2016",DRVGR2016,84,Frequently used derived variables (GR) 150% of...,Table contains the graduation rates derived fr...,Provisional,December 2017
33,90,9,Human Resources,Fall 2016,EAP2016,90,"Number of staff by occupational category, facu...",This table contains the number of staff classi...,Provisional,December 2017
34,90,9,Human Resources,2016-17,SAL2016_IS,91,Number and salary outlays for full-time nonmed...,"This table contains the number of staff, tota...",Provisional,December 2017
35,90,9,Human Resources,2016-17,SAL2016_NIS,92,Number and salary outlays for full-time nonmed...,This table contains the number and salary outl...,Provisional,December 2017
36,90,9,Human Resources,Fall 2016,S2016_OC,93,Full- and part-time staff by occupational cate...,This table contains the number of staff on the...,Provisional,December 2017
37,90,9,Human Resources,Fall 2016,S2016_SIS,94,"Full-time instructional staff, by academic ran...",This table contains the number of full-time in...,Provisional,December 2017
38,90,9,Human Resources,Fall 2016,S2016_IS,95,"Full-time instructional staff, by faculty and ...",This table contains the number of full-time in...,Provisional,December 2017
39,90,9,Human Resources,Fall 2016,S2016_NH,96,"New hires by occupational category, race/ethni...",This table contains the number of full-time ne...,Provisional,December 2017
40,90,9,Human Resources,Fall 2016,DRVHR2016,97,Frequently used/derived variables Human resour...,Table contains average salaries equated to 9-m...,Provisional,December 2017
41,12,12,Admissions,Academic year Fall 2016,ADM2016,120,"Admission considerations, applicants, admissio...",This table contains information about the unde...,Provisional,December 2017
42,12,12,Admissions,Academic year Fall 2016,DRVADM2016,121,Frequently used derived variables for admissio...,This table contains derived variables using th...,Provisional,December 2017
43,14,14,12-month Enrollment,"July 1, 2015 - June 30, 2016",EFFY2016,140,12-month unduplicated headcount: 2015-16,This table contains the unduplicated head coun...,Provisional,January 2018
44,14,14,12-month Enrollment,"July 1, 2015 - June 30, 2016",EFIA2016,141,12-month instructional activity: 2015-16,This table contains data on instructional acti...,Provisional,January 2018
45,14,14,12-month Enrollment,"July 1, 2015 - June 30, 2016",DRVEF122016,142,Frequently used derived variables (E12): 12-mo...,This table contains the unduplicated head coun...,Provisional,January 2018
46,100,16,Academic Libraries,2016-17,AL2016,160,"Academic Libraries, 2015-16",The Academic Library survey became part of the...,Provisional,December 2017
47,100,16,Academic Libraries,2016-17,DRVAL2016,161,Frequently used/derived variables Academic lib...,Table contains the percent distribution of lib...,Provisional,December 2017
48,55,18,Outcome Measures,"Status of student as of August 31, 2016",OM2016,181,Award and enrollment data at six and eight yea...,This table contains award and enrollment data ...,Provisional,December 2017
49,55,18,Outcome Measures,"Status of student as of August 31, 2016",DRVOM2016,182,Frequently used derived variables (OM) Award a...,This table contains award and enrollment rates...,Provisional,None